version: "3"
services:
  client:
    image: "emmrysjay/multi_client"
    mem_limit: 128m
    hostname: client
    #container_name: client
  server:
    image: "emmrysjay/multi_server"
    mem_limit: 128m
    hostname: api
    #container_name: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "emmrysjay/multi_worker"
    mem_limit: 128m
    hostname: worker
    #container_name: worker
    environment:
      - REDIS_HOST=$REDIS_HOST  
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "emmrysjay/multi_nginx"
    mem_limit: 128m
    hostname: nginx
   # container_name: nginx
    ports:
      - "80:80"


