name: Deploy Multi-Container Project
on: 
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files 
        uses: actions/checkout@v2

      - name: Test react
        run: |
          docker build -t emmrysjay/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true emmrysjay/react-test npm test
    
      - name: Generate production docker files
        run: |
          docker build -t emmrysjay/multi_server ./server
          docker build -t emmrysjay/multi_worker ./worker
          docker build -t emmrysjay/multi_nginx ./nginx
          docker build -t emmrysjay/multi_client ./client

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker images
        run: |
          docker push emmrysjay/multi_server
          docker push emmrysjay/multi_worker
          docker push emmrysjay/multi_nginx
          docker push emmrysjay/multi_client

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-362834013229
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip